# action.yml
name: "conventionalcommits-checker"
author: BLumia
branding:
  icon: "check"
  color: "black"
description: "check commits insider a Pull Request and see if it matches Conventional Commits guideline"
inputs:
  github_token:
    description: "action github token"
    required: false

runs:
  using: "composite"
  steps:
    - name: install git
      shell: bash
      run: |
        sudo apt-get install -y -q git
    - name: install golang
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19
    - name: run commitlint
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        go run ./conventionalcommits-checker/ -repo-dir $GITHUB_WORKSPACE -base-sha ${{ github.event.pull_request.base.sha }} -head-sha ${{ github.event.pull_request.head.sha }}

